import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
	container: {
		position: "absolute",
		bottom: 0,
		backgroundColor: "#fff",
		width: 375,
		height: 489,
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		borderTopRightRadius: 25,
		borderTopLeftRadius: 25,
		paddingLeft: 16,
		paddingRight: 16,
	},
	title: {
		fontWeight: "bold",
		fontSize: 30,
		paddingBottom: 32,
	},
	input: {
		borderWidth: 1,
		borderRadius: 8,
		borderColor: "#e8e8e8",
		padding: 16,
		width: 343,
		height: 50,
		marginBottom: 16,
		fontWeight: "400",
		fontSize: 16,
		lineHeight: 1.17,
	},
	inputNoFocus: {
		borderWidth: 1,
		borderRadius: 8,
		padding: 16,
		width: 343,
		height: 50,
		marginBottom: 16,
		fontWeight: "400",
		fontSize: 16,
		lineHeight: 1.17,
		borderColor: "#FF6C00",
	},
	passwordWrapper: {
		display: "flex",
		flexDirection: "row",
	},
	show: {
		color: "#1B4371",
		position: "absolute",
		right: 0,
		bottom: "50%",
		paddingRight: 16,
	},
	enter: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		width: 343,
		height: 51,
		color: "#fff",
		backgroundColor: "#FF6C00",
		fontWeight: "400",
		fontSize: 16,
		lineHeight: 1.17,
		marginBottom: 16,
		borderRadius: 100,
	},
	enterText: {
		color: "#fff",
	},
	signup: {
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		fontWeight: "400",
		fontSize: 16,
		lineHeight: 1.17,
		color: "#1B4371",
	},
	signupText: {
		marginRight: 10,
	},
});
