import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
	container: {
		width: "100%",
		height: "100%",
		paddingTop: 10,
		paddingLeft: 16,
		paddingRight: 16,
		backgroundColor: "#fff",
	},
	placeholder: {
		width: 300,
		height: 200,
		borderRadius: 8,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 29,
		paddingLeft: 16,
		paddingRight: 16,
		borderWidth: 1,
		borderColor: "#e8e8e8",
	},
	iconWrapper: {
		width: 60,
		height: 60,
		borderRadius: 30,
		backgroundColor: "#fff",
		opacity: 0.9,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
	},
	wrapperText: {
		color: "#212121",
		fontSize: 16,
		fontWeight: "500",
		textAlign: "left",
		marginBottom: 16,
		borderBottomWidth: 0.5,
	},
	button: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		width: 343,
		height: 51,
		borderRadius: 100,
		padding: 16,
		backgroundColor: "#ff6c00",
		marginBottom: 32,
		marginTop: 32,
	},
});
